import { Category } from "./types";

export const TRUSTPILOT_CATEGORIES: Category[] = [
  {
    slug: "animals_pets",
    name: "Animals & Pets",
    children: [
      { slug: "animal_health", name: "Animal Health" },
      { slug: "animal_parks_zoo", name: "Animal Parks & Zoo" },
      { slug: "cats_dogs", name: "Cats & Dogs" },
      { slug: "horses_riding", name: "Horses & Riding" },
      { slug: "pet_services", name: "Pet Services" },
      { slug: "pet_stores", name: "Pet Stores" },
    ],
  },
  {
    slug: "beauty_wellbeing",
    name: "Beauty & Well-being",
    children: [
      { slug: "cosmetics_makeup", name: "Cosmetics & Makeup" },
      { slug: "hair_care_styling", name: "Hair Care & Styling" },
      { slug: "personal_care", name: "Personal Care" },
      { slug: "salons_clinics", name: "Salons & Clinics" },
      { slug: "tattoos_piercings", name: "Tattoos & Piercings" },
      { slug: "wellness_spa", name: "Wellness & Spa" },
      { slug: "yoga_meditation", name: "Yoga & Meditation" },
    ],
  },
  {
    slug: "business_services",
    name: "Business Services",
    children: [
      { slug: "administration_services", name: "Administration & Services" },
      { slug: "associations_centers", name: "Associations & Centers" },
      { slug: "hr_recruiting", name: "HR & Recruiting" },
      { slug: "import_export", name: "Import & Export" },
      { slug: "it_communication", name: "IT & Communication" },
      { slug: "office_space_supplies", name: "Office Space & Supplies" },
      { slug: "print_graphic_design", name: "Print & Graphic Design" },
      { slug: "research_development", name: "Research & Development" },
      { slug: "sales_marketing", name: "Sales & Marketing" },
      { slug: "shipping_logistics", name: "Shipping & Logistics" },
      { slug: "wholesale", name: "Wholesale" },
    ],
  },
  {
    slug: "construction_manufactoring",
    name: "Construction & Manufacturing",
    children: [
      { slug: "architects_engineers", name: "Architects & Engineers" },
      { slug: "building_materials", name: "Building Materials" },
      { slug: "chemicals_plastic", name: "Chemicals & Plastic" },
      { slug: "construction_services", name: "Construction Services" },
      { slug: "contractors_consultants", name: "Contractors & Consultants" },
      { slug: "factory_equipment", name: "Factory Equipment" },
      { slug: "garden_landscaping", name: "Garden & Landscaping" },
      { slug: "industrial_supplies", name: "Industrial Supplies" },
      { slug: "manufacturing", name: "Manufacturing" },
      { slug: "production_services", name: "Production Services" },
      { slug: "tools_equipment", name: "Tools & Equipment" },
    ],
  },
  {
    slug: "education_training",
    name: "Education & Training",
    children: [
      { slug: "colleges_universities", name: "Colleges & Universities" },
      { slug: "courses_classes", name: "Courses & Classes" },
      { slug: "education_services", name: "Education Services" },
      { slug: "language_learning", name: "Language Learning" },
      { slug: "music_theater_classes", name: "Music & Theater Classes" },
      { slug: "school_high_school", name: "School & High School" },
      { slug: "specials_schools", name: "Special Schools" },
      { slug: "vocational_training", name: "Vocational Training" },
    ],
  },
  {
    slug: "electronics_technology",
    name: "Electronics & Technology",
    children: [
      { slug: "appliances_electronics", name: "Appliances & Electronics" },
      { slug: "audio_visual", name: "Audio & Visual" },
      { slug: "computers_phones", name: "Computers & Phones" },
      { slug: "internet_software", name: "Internet & Software" },
      { slug: "repair_services", name: "Repair & Services" },
    ],
  },
  {
    slug: "events_entertainment",
    name: "Events & Entertainment",
    children: [
      { slug: "adult_entertainment", name: "Adult Entertainment" },
      { slug: "childrens_entertainment", name: "Children's Entertainment" },
      { slug: "clubbing_nightlife", name: "Clubbing & Nightlife" },
      { slug: "events_venues", name: "Events & Venues" },
      { slug: "gambling", name: "Gambling" },
      { slug: "gaming", name: "Gaming" },
      { slug: "museums_exibits", name: "Museums & Exhibits" },
      { slug: "music_movies", name: "Music & Movies" },
      { slug: "theater_opera", name: "Theater & Opera" },
      { slug: "wedding_party", name: "Wedding & Party" },
    ],
  },
  {
    slug: "food_beverages_tobacco",
    name: "Food, Beverages & Tobacco",
    children: [
      { slug: "agriculture_produce", name: "Agriculture & Produce" },
      { slug: "asian_grocery_stores", name: "Asian Grocery Stores" },
      { slug: "bakery_pastry", name: "Bakery & Pastry" },
      { slug: "beer_wine", name: "Beer & Wine" },
      { slug: "beverages_liquor", name: "Beverages & Liquor" },
      { slug: "candy_chocolate", name: "Candy & Chocolate" },
      { slug: "coffee_tea", name: "Coffee & Tea" },
      { slug: "food_production", name: "Food Production" },
      { slug: "fruits_vegetables", name: "Fruits & Vegetables" },
      { slug: "grocery_stores_markets", name: "Grocery Stores & Markets" },
      { slug: "lunch_catering", name: "Lunch & Catering" },
      { slug: "meat_seafood_eggs", name: "Meat, Seafood & Eggs" },
      { slug: "smoking_tobacco", name: "Smoking & Tobacco" },
    ],
  },
  {
    slug: "health_medical",
    name: "Health & Medical",
    children: [
      { slug: "clinics", name: "Clinics" },
      { slug: "dental_services", name: "Dental Services" },
      { slug: "diagnostics_testing", name: "Diagnostics & Testing" },
      { slug: "doctors_surgeons", name: "Doctors & Surgeons" },
      { slug: "health_equipment", name: "Health Equipment" },
      { slug: "hospital_emergency", name: "Hospital & Emergency" },
      { slug: "medical_specialists", name: "Medical Specialists" },
      { slug: "mental_health", name: "Mental Health" },
      { slug: "pharmacy_medicine", name: "Pharmacy & Medicine" },
      { slug: "physical_aids", name: "Physical Aids" },
      { slug: "pregnancy_children", name: "Pregnancy & Children" },
      { slug: "therapy_senior_health", name: "Therapy & Senior Health" },
      { slug: "vision_hearing", name: "Vision & Hearing" },
    ],
  },
  {
    slug: "hobbies_crafts",
    name: "Hobbies & Crafts",
    children: [
      { slug: "art_handicraft", name: "Art & Handicraft" },
      { slug: "astrology_numerology", name: "Astrology & Numerology" },
      { slug: "fishing_hunting", name: "Fishing & Hunting" },
      { slug: "hobbies", name: "Hobbies" },
      { slug: "metal_stone_glass_work", name: "Metal, Stone & Glass Work" },
      { slug: "music_instruments", name: "Music & Instruments" },
      { slug: "needlework_knitting", name: "Needlework & Knitting" },
      { slug: "outdoor_activities", name: "Outdoor Activities" },
      { slug: "painting_paper", name: "Painting & Paper" },
    ],
  },
  {
    slug: "home_garden",
    name: "Home & Garden",
    children: [
      { slug: "bathroom_kitchen", name: "Bathroom & Kitchen" },
      { slug: "cultural_goods", name: "Cultural Goods" },
      { slug: "decoration_interior", name: "Decoration & Interior" },
      { slug: "energy_heating", name: "Energy & Heating" },
      { slug: "fabric_stationary", name: "Fabric & Stationery" },
      { slug: "furniture_stores", name: "Furniture Stores" },
      { slug: "garden_pond", name: "Garden & Pond" },
      { slug: "home_garden_services", name: "Home & Garden Services" },
      { slug: "home_goods_stores", name: "Home Goods Stores" },
      { slug: "home_improvements", name: "Home Improvements" },
    ],
  },
  {
    slug: "home_services",
    name: "Home Services",
    children: [
      { slug: "cleaning_service_providers", name: "Cleaning Service Providers" },
      { slug: "craftsman", name: "Craftsman" },
      { slug: "house_services", name: "House Services" },
      { slug: "house_sitting_security", name: "House Sitting & Security" },
      { slug: "moving_storage", name: "Moving & Storage" },
      { slug: "plumbing_sanitation", name: "Plumbing & Sanitation" },
      { slug: "repair_service_providers", name: "Repair Service Providers" },
    ],
  },
  {
    slug: "legal_services_government",
    name: "Legal Services & Government",
    children: [
      { slug: "customs_toll", name: "Customs & Toll" },
      { slug: "government_department", name: "Government Department" },
      { slug: "law_enforcement", name: "Law Enforcement" },
      { slug: "lawyers_attorneys", name: "Lawyers & Attorneys" },
      { slug: "legal_service_providers", name: "Legal Service Providers" },
      { slug: "libraries_archives", name: "Libraries & Archives" },
      { slug: "municipal_department", name: "Municipal Department" },
      { slug: "registration_services", name: "Registration Services" },
    ],
  },
  {
    slug: "media_publishing",
    name: "Media & Publishing",
    children: [
      { slug: "books_magazines", name: "Books & Magazines" },
      { slug: "media_information", name: "Media & Information" },
      { slug: "photography", name: "Photography" },
      { slug: "video_sound", name: "Video & Sound" },
    ],
  },
  {
    slug: "money_insurance",
    name: "Money & Insurance",
    children: [
      { slug: "accounting_tax", name: "Accounting & Tax" },
      { slug: "banking_money", name: "Banking & Money" },
      { slug: "credit_debt_services", name: "Credit & Debt Services" },
      { slug: "insurance", name: "Insurance" },
      { slug: "investments_wealth", name: "Investments & Wealth" },
      { slug: "real_estate", name: "Real Estate" },
    ],
  },
  {
    slug: "public_local_services",
    name: "Public & Local Services",
    children: [
      { slug: "employment_career", name: "Employment & Career" },
      { slug: "funeral_memorial", name: "Funeral & Memorial" },
      { slug: "housing_associations", name: "Housing Associations" },
      { slug: "kids_family", name: "Kids & Family" },
      { slug: "military_veteran", name: "Military & Veteran" },
      { slug: "nature_environment", name: "Nature & Environment" },
      { slug: "professional_organizations", name: "Professional Organizations" },
      { slug: "public_services_welfare", name: "Public Services & Welfare" },
      { slug: "religious_institutions", name: "Religious Institutions" },
      { slug: "shelters_homes", name: "Shelters & Homes" },
      { slug: "waste_management", name: "Waste Management" },
    ],
  },
  {
    slug: "restaurants_bars",
    name: "Restaurants & Bars",
    children: [
      { slug: "african_pacific_cuisine", name: "African & Pacific Cuisine" },
      { slug: "bars_cafes", name: "Bars & Cafes" },
      { slug: "chinese_korean_cuisine", name: "Chinese & Korean Cuisine" },
      { slug: "european_cuisine", name: "European Cuisine" },
      { slug: "general_restaurants", name: "General Restaurants" },
      { slug: "japanese_cuisine", name: "Japanese Cuisine" },
      { slug: "mediterranean_cuisine", name: "Mediterranean Cuisine" },
      { slug: "middle_eastern_cuisine", name: "Middle Eastern Cuisine" },
      { slug: "north_south_american_cuisine", name: "North & South American Cuisine" },
      { slug: "southeast_asian_cuisine", name: "Southeast Asian Cuisine" },
      { slug: "takeaway", name: "Takeaway" },
      { slug: "vegetarian_diet", name: "Vegetarian & Diet" },
    ],
  },
  {
    slug: "shopping_fashion",
    name: "Shopping & Fashion",
    children: [
      { slug: "accessories", name: "Accessories" },
      { slug: "clothing_underwear", name: "Clothing & Underwear" },
      { slug: "clothing_rental_repair", name: "Clothing Rental & Repair" },
      { slug: "costume_wedding", name: "Costume & Wedding" },
      { slug: "jewelry_watches", name: "Jewelry & Watches" },
      { slug: "malls_marketplaces", name: "Malls & Marketplaces" },
    ],
  },
  {
    slug: "sports",
    name: "Sports",
    children: [
      { slug: "ball_games", name: "Ball Games" },
      { slug: "bat-and-ball_games", name: "Bat-and-ball Games" },
      { slug: "bowls_lawn_sports", name: "Bowls & Lawn Sports" },
      { slug: "dancing_gymnastics", name: "Dancing & Gymnastics" },
      { slug: "equipment_associations", name: "Equipment & Associations" },
      { slug: "extreme_sports", name: "Extreme Sports" },
      { slug: "fitness_weight_lifting", name: "Fitness & Weight Lifting" },
      { slug: "golf_ultimate", name: "Golf & Ultimate" },
      { slug: "hockey_ice_skating", name: "Hockey & Ice Skating" },
      { slug: "martial_arts_wrestling", name: "Martial Arts & Wrestling" },
      { slug: "outdoor_winter_sports", name: "Outdoor & Winter Sports" },
      { slug: "shooting_target_sports", name: "Shooting & Target Sports" },
      { slug: "swimming_water_sports", name: "Swimming & Water Sports" },
      { slug: "tennis_racquet_sports", name: "Tennis & Racquet Sports" },
    ],
  },
  {
    slug: "travel_vacation",
    name: "Travel & Vacation",
    children: [
      { slug: "accomodations_lodging", name: "Accommodation & Lodging" },
      { slug: "activities_tours", name: "Activities & Tours" },
      { slug: "airlines_air_travel", name: "Airlines & Air Travel" },
      { slug: "hotels", name: "Hotels" },
      { slug: "travel_agencies", name: "Travel Agencies" },
    ],
  },
  {
    slug: "utilities",
    name: "Utilities",
    children: [
      { slug: "energy_power", name: "Energy & Power" },
      { slug: "oil_fuel", name: "Oil & Fuel" },
      { slug: "water_utilities", name: "Water Utilities" },
    ],
  },
  {
    slug: "vehicles_transportation",
    name: "Vehicles & Transportation",
    children: [
      { slug: "air_water_transport", name: "Air & Water Transport" },
      { slug: "airports_parking", name: "Airports & Parking" },
      { slug: "auto_parts_wheels", name: "Auto Parts & Wheels" },
      { slug: "bicycles", name: "Bicycles" },
      { slug: "cars_trucks", name: "Cars & Trucks" },
      { slug: "motorcycle_powersports", name: "Motorcycle & Powersports" },
      { slug: "other_vehicles_trailers", name: "Other Vehicles & Trailers" },
      { slug: "taxis_public_transport", name: "Taxis & Public Transport" },
      { slug: "vehical_rental", name: "Vehicle Rental" },
      { slug: "vehicle_repair_fuel", name: "Vehicle Repair & Fuel" },
    ],
  },
];

export function getAllCategories(): Category[] {
  return TRUSTPILOT_CATEGORIES;
}

export function getFlatCategories(): { slug: string; name: string; parent?: string }[] {
  const flat: { slug: string; name: string; parent?: string }[] = [];
  for (const cat of TRUSTPILOT_CATEGORIES) {
    flat.push({ slug: cat.slug, name: cat.name });
    if (cat.children) {
      for (const child of cat.children) {
        flat.push({ slug: child.slug, name: child.name, parent: cat.name });
      }
    }
  }
  return flat;
}
